spring.application.name=NexusA

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/nexus_db
spring.datasource.username=postgres
spring.datasource.password=38617
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT
jwt.secret=bng5ZjJrOHZRcExtUjN0WXdaYUI3Y0RoSmVHaUtvVXM=
jwt.expiration=86400000

ror.base.url=https://api.ror.org
spring.main.allow-bean-definition-overriding=true
