spring.application.name=NexusA

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/nexus_db
spring.datasource.username=postgres
spring.datasource.password=sontya48go
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT
jwt.secret=bng5ZjJrOHZRcExtUjN0WXdaYUI3Y0RoSmVHaUtvVXM=
jwt.expiration=86400000

ror.base.url=https://api.ror.org
spring.main.allow-bean-definition-overriding=true

llm.provider=groq
groq.api.key=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
groq.model=llama-3.1-8b-instant
llm.model=llama-3.1-8b-instant
